spring:
  main:
    allow-bean-definition-overriding: 'true'
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?createDatabaseIfNotExist=true
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: create
    open-in-view: 'false'
    properties:
      hibernate:
        format_sql: 'true'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
springboot:
  jwt:
    secret: ${JWT_SECRET}
server:
  port: ${SERVER_PORT}