name: Gradle CI & CD

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  CICD:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Create application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML_CONTENT }}" > src/main/resources/application.yml

      - name: Grant execute permission for gradlew
        run: |
          cd favor
          chmod +x gradlew

      - name: Build with Gradle
        run: |
          cd favor
          ./gradlew clean bootJar

      - name: Shutdown Old Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
              PID=$(ps -ef | grep "$SERVICE_NAME" | awk "$3 == 1 {print $2}")
              if [[ -n "$PID" ]]; then
                echo "프로세스를 종료합니다: $PID"
                kill -9 "$PID"
              else
                echo "프로세스가 이미 종료되었습니다."
              fi
        env:
          APP_DIRECTORY: ${{ secrets.APP_DIRECTORY }}
          FILE_NAME: ${{ secrets.FILE_NAME }}

      - name: Move New Service
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "build/libs/*.jar"
          target: $TARGET_DIRECTORY
          rm: true
        env:
          TARGET_DIRECTORY: ${{ secrets.APP_DIRECTORY }}

      - name: Run New Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd $APP_DIRECTORY
            nohup java -jar $FILENAME
        env:
          APP_DIRECTORY: ${{ secrets.APP_DIRECTORY }}
          FILE_NAME: ${{ secrets.FILE_NAME }}
