name: Gradle CI & CD

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  Build and Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Create application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML_CONTENT }}" > src/main/resources/application.yml

      - name: Grant execute permission for gradlew
        run: |
          cd favor
          chmod +x gradlew

      - name: Build with Gradle
        env:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          cd favor
          ./gradlew jib

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port : ${{ secrets.SERVER_PORT }}
          script: |
            docker stop ${{ secrets.APPLICATION_NAME }}
            docker rm ${{ secrets.APPLICATION_NAME }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
            docker run -d -p ${{ secrets.DEPLOY_PORT }}:8080 -e TZ=Asia/Seoul --name ${{ secrets.APPLICATION_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
