name: Gradle CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Create properties
        run: |
          cd favor
          echo "${{ secrets.GRADLE_PROPERTIES_CONTENT }}" > gradle.properties
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML_CONTENT }}" > src/main/resources/application.yml

      - name: Grant execute permission for gradlew
        run: |
          cd favor
          chmod +x gradlew

      - name: Build with Gradle
        run: |
          cd favor
          ./gradlew bootJar
